### ISSUE TITLE
Configuration for Mysql

### ISSUE THREAD

**Issue by chiqui3d** [FoalTS/foal#442]
I hope this helps to configure your application with Mysql and TypeOrm.

**ormconfig.yml** (Configure to your liking or use ormconfig.json)
```
default:
  type: mysql
  database: yourdatabese
  host: localhost
  port: 3306
  username: root
  password: yourpassword
  entities: [ build/Entity/**/*.js ]
  subscribers: [ build/Subscriber/**/*.js ]
  migrations: [ build/Migration/**/*.js ]
  cli:
    migrationsDir: src/Migration
    entitiesDir: src/Entity
    subscribersDir: src/Subscriber
  synchronize: true
  logging: false
```
**index.ts**

```
import 'source-map-support/register';

// std
import * as http from 'http';

// 3p
import { Config, createApp } from '@foal/core';
import {createConnection} from 'typeorm';

// App
import { AppController } from './app.controller';

createConnection().then(connection => {
  const app = createApp(AppController);
  const httpServer = http.createServer(app);
  const port = Config.get('port', 3001);
  httpServer.listen(port, () => {
    console.log(`Listening on port ${port}...`);
  });
});
```

**UserController:**
```

import { Get, HttpResponseOK, HttpResponseNotFound } from '@foal/core';
import { User} from '../Entity/User';
import { getRepository } from 'typeorm';

export class UserController {

  @Get('/')
  async index(ctx) {
    const user= await getRepository(User).findOne(1);
    if(!user){
      return new HttpResponseNotFound('Not User Found');
    }
    return new HttpResponseOK(user);
  }

}
```
